/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TodoRouteImport } from './routes/todo'
import { Route as NotepadRouteImport } from './routes/notepad'
import { Route as GoalRouteImport } from './routes/goal'
import { Route as IndexRouteImport } from './routes/index'
import { Route as NotepadShareTokenRouteImport } from './routes/notepad.share.$token'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as BlogAdminRouteImport } from './routes/blog/admin'
import { Route as BlogSlugRouteImport } from './routes/blog/$slug'

const TodoRoute = TodoRouteImport.update({
  id: '/todo',
  path: '/todo',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepadRoute = NotepadRouteImport.update({
  id: '/notepad',
  path: '/notepad',
  getParentRoute: () => rootRouteImport,
} as any)
const GoalRoute = GoalRouteImport.update({
  id: '/goal',
  path: '/goal',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const NotepadShareTokenRoute = NotepadShareTokenRouteImport.update({
  id: '/notepad/share/$token',
  path: '/notepad/share/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogAdminRoute = BlogAdminRouteImport.update({
  id: '/blog/admin',
  path: '/blog/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/notepad': typeof NotepadRoute
  '/todo': typeof TodoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/notepad/share/$token': typeof NotepadShareTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/notepad': typeof NotepadRoute
  '/todo': typeof TodoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog': typeof BlogIndexRoute
  '/notepad/share/$token': typeof NotepadShareTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/goal': typeof GoalRoute
  '/notepad': typeof NotepadRoute
  '/todo': typeof TodoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/blog/admin': typeof BlogAdminRoute
  '/blog/': typeof BlogIndexRoute
  '/notepad/share/$token': typeof NotepadShareTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/goal'
    | '/notepad'
    | '/todo'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog/'
    | '/notepad/share/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/goal'
    | '/notepad'
    | '/todo'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog'
    | '/notepad/share/$token'
  id:
    | '__root__'
    | '/'
    | '/goal'
    | '/notepad'
    | '/todo'
    | '/blog/$slug'
    | '/blog/admin'
    | '/blog/'
    | '/notepad/share/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GoalRoute: typeof GoalRoute
  NotepadRoute: typeof NotepadRoute
  TodoRoute: typeof TodoRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BlogAdminRoute: typeof BlogAdminRoute
  BlogIndexRoute: typeof BlogIndexRoute
  NotepadShareTokenRoute: typeof NotepadShareTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/todo': {
      id: '/todo'
      path: '/todo'
      fullPath: '/todo'
      preLoaderRoute: typeof TodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notepad': {
      id: '/notepad'
      path: '/notepad'
      fullPath: '/notepad'
      preLoaderRoute: typeof NotepadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/goal': {
      id: '/goal'
      path: '/goal'
      fullPath: '/goal'
      preLoaderRoute: typeof GoalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notepad/share/$token': {
      id: '/notepad/share/$token'
      path: '/notepad/share/$token'
      fullPath: '/notepad/share/$token'
      preLoaderRoute: typeof NotepadShareTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/admin': {
      id: '/blog/admin'
      path: '/blog/admin'
      fullPath: '/blog/admin'
      preLoaderRoute: typeof BlogAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GoalRoute: GoalRoute,
  NotepadRoute: NotepadRoute,
  TodoRoute: TodoRoute,
  BlogSlugRoute: BlogSlugRoute,
  BlogAdminRoute: BlogAdminRoute,
  BlogIndexRoute: BlogIndexRoute,
  NotepadShareTokenRoute: NotepadShareTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
